name: get spotify charts data

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  run-python:
    name: set up python and run main.py
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: pip install packages
        run: pip3 install -r requirements.txt
      - name: run main.py
        env:
          SPOTIFY_API_CLIENT_ID: ${{ secrets.SPOTIFY_API_CLIENT_ID }}
          SPOTIFY_API_CLIENT_SECRET: ${{ secrets.SPOTIFY_API_CLIENT_SECRET }}
        run: cd src && python3 main.py
      - name: git push
        env:
          EMAIL_ADDR: ${{ secrets.EMAIL_ADDR }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          git config --global user.email $EMAIL_ADDR
          git config --global user.name $USERNAME
          git add .
          git commit -m "[add]: add data by schedule-test workflow 'get spotify charts data'"
          git push origin master
